#!/usr/bin/env bash

## The branch name must meet the git-flow requirements.
#LC_ALL=C
#
#local_branch="$(git symbolic-ref --short -q HEAD)"
#valid_branch_regex="^(master|develop)$|(feature|release|hotfix)\/[a-z0-9._-]+$"
#
#message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex.
#Your commit will be rejected. You should rename your branch to a valid name and try again."
#
#if [[ ! $local_branch =~ $valid_branch_regex ]]
#then
#    echo "$message"
#    exit 1
#fi
#
#exit 0
